import tkinter.messagebox as msg
from tkinter import Menu
import customtkinter
from PIL import Image
customtkinter.set_appearance_mode("dark")
customtkinter.set_default_color_theme("dark-blue")
moiz = customtkinter.CTk()
moiz.geometry("350x350")
moiz.minsize(350,350)
moiz.maxsize(350,350)
moiz.title("Mattress")
moiz.iconbitmap("logo/App_logo.ico")
# === Image ===
dia_pic = customtkinter.CTkImage(dark_image=Image.open('logo/Img_logo.png'),size=(150,150))
dia_img = customtkinter.CTkLabel(moiz,text="",image=dia_pic)
dia_img.place(x=110,y=20)
# === Function ===
def run():
    if ue.get() != "moiz":
        return msg.showinfo("Error", "       4 0 4\n Username Error")
    elif pe.get() != "346":
        return msg.showinfo("Error", "       4 0 4\n Password Error")
    else:
        return inventory()
    
# Entering in TopLevel
customtkinter.CTkLabel(master=moiz, text="Username", width=130,fg_color='red',text_color='black',corner_radius=6,font=customtkinter.CTkFont('Ink Free',19)).place(x=20, y=190)
customtkinter.CTkLabel(master=moiz, text="Password", width=130,fg_color='red',text_color='black',corner_radius=6,font=customtkinter.CTkFont('Ink Free',19)).place(x=20, y=250)
user = customtkinter.StringVar()
phn = customtkinter.StringVar()
ue = customtkinter.CTkEntry(moiz, textvariable=user)
ue.place(x=160, y=190)
pe = customtkinter.CTkEntry(moiz, textvariable=phn)
pe.place(x=160, y=250)
customtkinter.CTkButton(master=moiz,text="Enter", command=run,fg_color='white',hover_color='red',text_color='black',font=customtkinter.CTkFont('Courier New',17)).place(x=100,y=300)

def inventory():
    moiz.withdraw()
    new = customtkinter.CTkToplevel(moiz)
    new.geometry("400x300")
    new.minsize(400,300)
    new.maxsize(400,300)
    new.title("Inventory")
    new.iconbitmap("logo/App_logo.ico")
    stock = customtkinter.CTkButton(master=new,text="S T O C K",command=STOCK,hover_color='white',text_color='black',fg_color='red',font=customtkinter.CTkFont('Segoe UI',16),width=150)
    stock.place(x=130,y=100)
    challan = customtkinter.CTkButton(master=new,text="C H A L L A N",command=CHALLAN,hover_color='white',text_color='black',fg_color='red',font=customtkinter.CTkFont('Segoe UI',16),width=150)
    challan.place(x=130,y=150)
    bill = customtkinter.CTkButton(master=new,text="B I L L",command=BILL,hover_color='white',text_color='black',fg_color='red',font=customtkinter.CTkFont('Segoe UI',16),width=150)
    bill.place(x=130,y=50)
    
def BILL():
    # === Stock Bill Window ===
    stock_bill = customtkinter.CTkToplevel(moiz)
    stock_bill.geometry("650x500")
    stock_bill.minsize(650,500)
    stock_bill.maxsize(650,500)
    stock_bill.title("BILL")
    stock_bill.iconbitmap("logo/App_logo.ico")
    # === Shop Name ===
    head = customtkinter.CTkLabel(stock_bill,text="MOIZ  FOAM  CENTRE\t",width=400,height=60,fg_color='red',text_color='white',corner_radius=7,font=customtkinter.CTkFont("Freestyle Script",32,'bold'))
    head.place(x=20,y=20)
    head_line = customtkinter.CTkLabel(head,text="",fg_color='black',height=1,width=375,corner_radius=6)
    head_line.place(x=20,y=45)
    # === Frames ===
    quality_frame= customtkinter.CTkFrame(stock_bill,width=450,height=300,fg_color='dark grey',corner_radius=6)
    quality_frame.place(x=15,y=100)
    quantity_frame= customtkinter.CTkFrame(stock_bill,width=150,height=300,fg_color='dark grey',corner_radius=6)
    quantity_frame.place(x=470,y=100)
    total_amount_frame= customtkinter.CTkFrame(stock_bill,width=150,height=40,fg_color='grey',corner_radius=6)
    total_amount_frame.place(x=470,y=405)
    # === Bill Template ===
    bill_qty = customtkinter.CTkLabel(quality_frame,text="Qty  ",text_color='white',bg_color='dark grey',fg_color='black',height=4,width=30,corner_radius=6,font=customtkinter.CTkFont('Segoe UI',15,'bold'))
    bill_qty.place(x=5,y=2)
    bill_name = customtkinter.CTkLabel(quality_frame,text="Name  ",bg_color='dark grey',text_color='white',fg_color='black',height=4,width=130,corner_radius=6,font=customtkinter.CTkFont('Segoe UI',15,'bold'))
    bill_name.place(x=60,y=2)
    bill_size = customtkinter.CTkLabel(quality_frame,text="Size  ",bg_color='dark grey',fg_color='black',text_color='white',height=4,width=120,corner_radius=6,font=customtkinter.CTkFont('Segoe UI',15,'bold'))
    bill_size.place(x=260,y=2)
    bill_price = customtkinter.CTkLabel(stock_bill,text="Price    ",text_color='white',bg_color='dark grey',fg_color='black',height=4,width=130,corner_radius=6,font=customtkinter.CTkFont('Segoe UI',15,'bold'))
    bill_price.place(x=472,y=102)
    
    # === Functions ===
    def add_one():
        option_one = customtkinter.CTkOptionMenu(quality_frame,values=select_option,width=160,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        size_one = customtkinter.CTkOptionMenu(quality_frame,values=select_size,width=150,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        qty_one = customtkinter.CTkOptionMenu(quality_frame,values=select_Qty,width=35,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        enter_one = customtkinter.CTkEntry(master=stock_bill,textvariable=total_val_one,corner_radius=7,bg_color='dark grey',fg_color='dark grey',width=148,font=customtkinter.CTkFont('Courier New',16,))
        option_one.place(x=62,y=55)
        size_one.place(x=260,y=55)
        qty_one.place(x=6,y=55)
        enter_one.place(x=472,y=155)
    def total_amount():
        try:
            n = int(Qty_option.get())
            m = int(total_val.get())
            multiply = n * m
            total = customtkinter.CTkLabel(stock_bill,text=multiply,width=140,bg_color='grey',text_color='black',fg_color='grey',font=customtkinter.CTkFont('Courier New',16,))
            total.place(x=480,y=410)
        except:
            msg.showinfo("Problem", "Write in numbers")
    
    def selected_option(selected):
        return selected
    
    def selected_size(size):
        return size
    def selected_Qty(Qty):
        return Qty
    
    # === Option Menu / Buttons ===
    select_option = ["Galaxy","Health Care","Spine Care","Choice","Lagoon","Superb","Diamond","A-One","Sleep Ease","Relax"]
    select_size = ["78 x 72 x 8","78 x 72 x 6","78 x 72 x 5","72 x 72 x 4","78 x 60 x 8","78 x 60 x 6","78 x 60 x 5","78 x 60 x 4","72 x 60 x 8","72 x 60 x 6","72 x 60 x 5","72 x 60 x 4","72 x 48 x 6","72 x 48 x 4","72 x 36 x 4",]
    select_Qty = ['1','2','3','4','5','6','7','8','9','10']
    total_val = customtkinter.StringVar()
    total_val_one = customtkinter.StringVar()
    Save_button = customtkinter.CTkButton(stock_bill,text="Save Bill",width=150,fg_color='red',text_color='white',hover_color='blue',font=customtkinter.CTkFont('Courier New',16,'bold'))
    add_button = customtkinter.CTkButton(stock_bill,text="Add",width=133,fg_color='red',text_color='white',hover_color='blue',font=customtkinter.CTkFont('Courier New',16,'bold'))
    total_amount_button = customtkinter.CTkButton(stock_bill,text="Total Amount",command=total_amount,width=150,fg_color='red',text_color='white',hover_color='blue',font=customtkinter.CTkFont('Courier New',16,'bold'))
    quality_option = customtkinter.CTkOptionMenu(quality_frame,values=select_option,command=selected_option,width=160,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
    quality_size = customtkinter.CTkOptionMenu(quality_frame,values=select_size,command=selected_size,width=150,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
    Qty_option = customtkinter.CTkOptionMenu(quality_frame,values=select_Qty,command=selected_Qty,width=35,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
    enter_value = customtkinter.CTkEntry(master=stock_bill,textvariable=total_val,corner_radius=7,bg_color='dark grey',text_color='black',fg_color='dark grey',width=148,font=customtkinter.CTkFont('Courier New',16,))
    add_button = customtkinter.CTkButton(stock_bill,text="Add",command=add_one,width=133,fg_color='red',text_color='white',hover_color='blue',font=customtkinter.CTkFont('Courier New',16,'bold'))
    add_button.place(x=175,y=405)
    Save_button.place(x=20,y=405)    
    add_button.place(x=175,y=405)    
    total_amount_button.place(x=312,y=405)
    quality_option.place(x=62,y=24)
    quality_size.place(x=260,y=24)
    Qty_option.place(x=6,y=24)
    enter_value.place(x=472,y=124)
    # === Image ===
    dia_pic = customtkinter.CTkImage(dark_image=Image.open('logo/Img_logo.png'),size=(80,80))
    dia_img = customtkinter.CTkLabel(stock_bill,text="",image=dia_pic)
    dia_img.place(x=500,y=15)

def CHALLAN():
    # === Challan Window === 
    challan = customtkinter.CTkToplevel(moiz)
    challan.geometry("700x600")
    challan.minsize(700,600)
    challan.maxsize(700,600)
    challan.title("CHALLAN")
    challan.iconbitmap("logo/App_logo.ico")
    challan_head = customtkinter.CTkLabel(challan,text="MOIZ FOAM CENTRE\t",width=400,height=60,fg_color='red',text_color='white',corner_radius=7,font=customtkinter.CTkFont("Freestyle Script",30,'bold'))
    challan_head.place(x=20,y=20)
    company_challan = customtkinter.CTkLabel(challan,text="COMPANY INVOICE",width=250,height=35,fg_color='black',text_color='white',corner_radius=7,font=customtkinter.CTkFont("Ink Free",24))
    company_challan.place(x=30,y=145)
    challan_no = customtkinter.CTkLabel(challan,text="Challan No:",width=100,height=25,fg_color='black',text_color='white',corner_radius=7,font=customtkinter.CTkFont("Ink Free",18))
    challan_no.place(x=400,y=120)
    # === Challan Number Entry
    no_entry = customtkinter.CTkEntry(challan,corner_radius=7,text_color='black',placeholder_text="Write Number",placeholder_text_color='black',fg_color='dark grey',width=150,height=35,font=customtkinter.CTkFont('Courier New',16))
    no_entry.place(x=400,y=145)
    # === Challan Date ===
    Date_DMY = customtkinter.CTkLabel(challan,text="Date: ",width=45,height=30,text_color='white',corner_radius=7,font=customtkinter.CTkFont("Ink Free",15,'bold'))
    Date_DMY.place(x=205,y=85)
    dd = customtkinter.CTkEntry(challan,corner_radius=7,text_color='black',placeholder_text="DD",placeholder_text_color='black',fg_color='dark grey',width=35,height=30,font=customtkinter.CTkFont('Courier New',16))
    mm = customtkinter.CTkEntry(challan,corner_radius=7,text_color='black',placeholder_text="MM",placeholder_text_color='black',fg_color='dark grey',width=35,height=30,font=customtkinter.CTkFont('Courier New',16))
    yy = customtkinter.CTkEntry(challan,corner_radius=7,text_color='black',placeholder_text="YY",placeholder_text_color='black',fg_color='dark grey',width=35,height=30,font=customtkinter.CTkFont('Courier New',16))
    dd.place(x=255,y=85)
    mm.place(x=290,y=85)
    yy.place(x=325,y=85)
    # === Frames ===
    frame = customtkinter.CTkFrame(challan,fg_color='dark grey',width=680,height=350)
    frame.place(x=10,y=188)
    qty_frame = customtkinter.CTkFrame(frame,fg_color='grey',width=90,height=345)
    qty_frame.place(x=3,y=3)
    name_frame = customtkinter.CTkFrame(frame,fg_color='grey',width=260,height=345)
    name_frame.place(x=97,y=3)
    size_frame  =customtkinter.CTkFrame(frame, fg_color='grey',width=220,height=345)
    size_frame.place(x=360,y=3)
    # === Image ===
    dia_pic = customtkinter.CTkImage(dark_image=Image.open('logo/Img_logo.png'),size=(100,100))
    dia_img = customtkinter.CTkLabel(challan,text="",image=dia_pic)
    dia_img.place(x=550,y=20)
    # === Functions ===
    def add_one():
        add_qty1 = customtkinter.CTkOptionMenu(qty_frame,values=qty,width=85,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_qty1.place(x=3,y=40)
        add_name1 = customtkinter.CTkOptionMenu(name_frame,values=name,width=250,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_name1.place(x=3,y=40)
        add_size1 = customtkinter.CTkOptionMenu(size_frame,values=size,width=210,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_size1.place(x=3,y=40)
        add_buttton1 = customtkinter.CTkButton(frame,command=add_two,fg_color='red',text='Add',width=96,text_color='white',hover_color='black',font=customtkinter.CTkFont('Courier New',16,'bold'))
        add_buttton1.place(x=582,y=42)
        
    def add_two():
        add_qty2 = customtkinter.CTkOptionMenu(qty_frame,values=qty,width=85,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_qty2.place(x=3,y=78)
        add_name2 = customtkinter.CTkOptionMenu(name_frame,values=name,width=250,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_name2.place(x=3,y=78)
        add_size2 = customtkinter.CTkOptionMenu(size_frame,values=size,width=210,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_size2.place(x=3,y=78)
        add_buttton2 = customtkinter.CTkButton(frame,command=add_three,fg_color='red',text='Add',width=96,text_color='white',hover_color='black',font=customtkinter.CTkFont('Courier New',16,'bold'))
        add_buttton2.place(x=582,y=78)
        
    def add_three():
        add_qty3 = customtkinter.CTkOptionMenu(qty_frame,values=qty,width=85,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_qty3.place(x=3,y=114)
        add_name3 = customtkinter.CTkOptionMenu(name_frame,values=name,width=250,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_name3.place(x=3,y=114)
        add_size3 = customtkinter.CTkOptionMenu(size_frame,values=size,width=210,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_size3.place(x=3,y=114)
        add_buttton3 = customtkinter.CTkButton(frame,command=add_four,fg_color='red',text='Add',width=96,text_color='white',hover_color='black',font=customtkinter.CTkFont('Courier New',16,'bold'))
        add_buttton3.place(x=582,y=114)
        
    def add_four():
        add_qty4 = customtkinter.CTkOptionMenu(qty_frame,values=qty,width=85,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_qty4.place(x=3,y=150)
        add_name4 = customtkinter.CTkOptionMenu(name_frame,values=name,width=250,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_name4.place(x=3,y=150)
        add_size4 = customtkinter.CTkOptionMenu(size_frame,values=size,width=210,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_size4.place(x=3,y=150)
        add_buttton4 = customtkinter.CTkButton(frame,command=add_five,fg_color='red',text='Add',width=96,text_color='white',hover_color='black',font=customtkinter.CTkFont('Courier New',16,'bold'))
        add_buttton4.place(x=582,y=150)
        
    def add_five():
        add_qty5 = customtkinter.CTkOptionMenu(qty_frame,values=qty,width=85,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_qty5.place(x=3,y=186)
        add_name5 = customtkinter.CTkOptionMenu(name_frame,values=name,width=250,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_name5.place(x=3,y=186)
        add_size5 = customtkinter.CTkOptionMenu(size_frame,values=size,width=210,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_size5.place(x=3,y=186)
        add_buttton5 = customtkinter.CTkButton(frame,command=add_six,fg_color='red',text='Add',width=96,text_color='white',hover_color='black',font=customtkinter.CTkFont('Courier New',16,'bold'))
        add_buttton5.place(x=582,y=186)
        
    def add_six():
        add_qty6 = customtkinter.CTkOptionMenu(qty_frame,values=qty,width=85,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_qty6.place(x=3,y=222)
        add_name6 = customtkinter.CTkOptionMenu(name_frame,values=name,width=250,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_name6.place(x=3,y=222)
        add_size6 = customtkinter.CTkOptionMenu(size_frame,values=size,width=210,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_size6.place(x=3,y=222)
        add_buttton6 = customtkinter.CTkButton(frame,command=add_seven,fg_color='red',text='Add',width=96,text_color='white',hover_color='black',font=customtkinter.CTkFont('Courier New',16,'bold'))
        add_buttton6.place(x=582,y=222)
    
    def add_seven():
        add_qty7 = customtkinter.CTkOptionMenu(qty_frame,values=qty,width=85,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_qty7.place(x=3,y=258)
        add_name7 = customtkinter.CTkOptionMenu(name_frame,values=name,width=250,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_name7.place(x=3,y=258)
        add_size7 = customtkinter.CTkOptionMenu(size_frame,values=size,width=210,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_size7.place(x=3,y=258)
        add_buttton7 = customtkinter.CTkButton(frame,command=add_eight,fg_color='red',text='Add',width=96,text_color='white',hover_color='black',font=customtkinter.CTkFont('Courier New',16,'bold'))
        add_buttton7.place(x=582,y=258)
        
    def add_eight():
        add_qty8 = customtkinter.CTkOptionMenu(qty_frame,values=qty,width=85,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_qty8.place(x=3,y=294)
        add_name8 = customtkinter.CTkOptionMenu(name_frame,values=name,width=250,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_name8.place(x=3,y=294)
        add_size8 = customtkinter.CTkOptionMenu(size_frame,values=size,width=210,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
        add_size8.place(x=3,y=294)
        
    # === Option Menu === 
        
    def save_challan():
        pass
    # === Button ===
    add_buttton = customtkinter.CTkButton(frame,command=add_one,fg_color='red',text='Add',width=96,text_color='white',hover_color='black',font=customtkinter.CTkFont('Courier New',16,'bold'))
    add_buttton.place(x=582,y=4)
    save_buttton = customtkinter.CTkButton(challan,command=save_challan,fg_color='red',text='Save Challan',width=100,height=30,text_color='white',hover_color='black',font=customtkinter.CTkFont('Courier New',16,'bold'))
    save_buttton.place(x=557,y=543)
    
    # === Option Menu === 
    name = ["Galaxy","Health Care","Spine Care","Choice","Lagoon","Superb","Diamond","A-One","Sleep Ease","Relax"]
    size = ["78 x 72 x 8","78 x 72 x 6","78 x 72 x 5","72 x 72 x 4","78 x 60 x 8","78 x 60 x 6","78 x 60 x 5","78 x 60 x 4","72 x 60 x 8","72 x 60 x 6","72 x 60 x 5","72 x 60 x 4","72 x 48 x 6","72 x 48 x 4","72 x 36 x 4",]
    qty = ['1','2','3','4','5','6','7','8','9','10']
    name_option = customtkinter.CTkOptionMenu(name_frame,values=name,width=250,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
    size_option = customtkinter.CTkOptionMenu(size_frame,values=size,width=210,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
    qty_option = customtkinter.CTkOptionMenu(qty_frame,values=qty,width=85,dropdown_fg_color='red',dropdown_text_color='white',dropdown_font=customtkinter.CTkFont('Courier New',16,),dropdown_hover_color='black',button_color='red',button_hover_color='black',fg_color='red',font=customtkinter.CTkFont('Courier New',16,))
    name_option.place(x=3,y=3)
    size_option.place(x=3,y=3)
    qty_option.place(x=3,y=3)

def STOCK():
    # === Stock Window === 
    stk = customtkinter.CTkToplevel(moiz)
    stk.geometry("1080x680")
    stk.minsize(1080,680)
    stk.maxsize(1080,680)
    stk.title("STOCK")
    stk.iconbitmap("logo/App_logo.ico")
    stk_head = customtkinter.CTkLabel(stk,text="   MOIZ FOAM CENTRE\t",width=400,height=50,fg_color='red',text_color='white',corner_radius=7,font=customtkinter.CTkFont("Freestyle Script",40,'bold'))
    stk_head.place(x=250,y=10)
    address = customtkinter.CTkLabel(stk,text="Address:  Sukkur, Sindh, Pakistan\t",width=200,height=20,text_color='white',font=customtkinter.CTkFont("Book Antiqua",16))
    address.place(x=300,y=67)
    dia_pic = customtkinter.CTkImage(dark_image=Image.open('logo/Img_logo.png'),size=(90,90))
    dia_img = customtkinter.CTkLabel(stk,text="",image=dia_pic)
    dia_img.place(x=25,y=10)
    # === Menu === 
    mainmenu  = Menu(stk)
    stk.config(menu=mainmenu)
    op1 = Menu(mainmenu)
    # === Frame === 
    heading = customtkinter.CTkFrame(stk,corner_radius=7,fg_color="white",height=35,width=1020)
    heading.place(x=10,y=108)
    body = customtkinter.CTkFrame(stk,corner_radius=7,fg_color="black",height=530,width=1030)
    body.place(x=7,y=147)
    # === Scrollbar ==
    # === Name ===
    size_inch = customtkinter.CTkLabel(stk,corner_radius=7,bg_color='white',fg_color="black",text=" S i z e ",font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=125)
    galaxy = customtkinter.CTkLabel(stk,corner_radius=7,bg_color='white',fg_color="red",text="Galaxy",font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    health_care = customtkinter.CTkLabel(stk,corner_radius=7,bg_color='white',fg_color="red",text="Health Care",font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    spine_care = customtkinter.CTkLabel(stk,corner_radius=7,fg_color="red",text="Spine Care",bg_color='white',font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    choice = customtkinter.CTkLabel(stk,corner_radius=7,fg_color="red",text="Choice",bg_color='white',font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    lagoon = customtkinter.CTkLabel(stk,corner_radius=7,fg_color="red",text="Lagoon",bg_color='white',font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    Superb = customtkinter.CTkLabel(stk,corner_radius=7,fg_color="red",text="Superb",bg_color='white',font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    diamond = customtkinter.CTkLabel(stk,corner_radius=7,fg_color="red",text="Diamond",bg_color='white',font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    aone = customtkinter.CTkLabel(stk,corner_radius=7,fg_color="red",text="A-One",bg_color='white',font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    sleep_ease = customtkinter.CTkLabel(stk,corner_radius=7,fg_color="red",text="Sleep Ease",bg_color='white',font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    relax = customtkinter.CTkLabel(stk,corner_radius=7,fg_color="red",text="Relax",bg_color='white',font=customtkinter.CTkFont('Bernard MT Condensed',18),text_color='white',height=30,width=80)
    size_inch.place(x=15,y=110)
    galaxy.place(x=150,y=110)
    health_care.place(x=245,y=110)
    spine_care.place(x=360,y=110)
    choice.place(x=449,y=110)
    lagoon.place(x=531,y=110)
    Superb.place(x=613,y=110)
    diamond.place(x=695,y=110)
    aone.place(x=777,y=110)
    sleep_ease.place(x=859,y=110)
    relax.place(x=947,y=110)
    # === Size ===
    s78728 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="78 x 72 x 8",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s78726 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="78 x 72 x 6",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s78725 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="78 x 72 x 5",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s78724 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="72 x 72 x 4",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s78608 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="78 x 60 x 8",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s78606 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="78 x 60 x 6",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s78605 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="78 x 60 x 5",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s78604 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="78 x 60 x 4",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s72608 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="72 x 60 x 8",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s72606 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="72 x 60 x 6",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s72605 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="72 x 60 x 5",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s72604 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="72 x 60 x 4",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s72486 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="72 x 48 x 6",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s72484 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="72 x 48 x 4",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s72364 = customtkinter.CTkLabel(body,corner_radius=7,fg_color="red",text="72 x 36 x 4",font=customtkinter.CTkFont('Courier New',18),text_color='white',height=30,width=80)
    s78728.place(x=10,y=5)
    s78726.place(x=10,y=40)
    s78725.place(x=10,y=75)
    s78724.place(x=10,y=110)
    s78608.place(x=10,y=145)
    s78606.place(x=10,y=180)
    s78605.place(x=10,y=215)
    s78604.place(x=10,y=250)
    s72608.place(x=10,y=285)
    s72606.place(x=10,y=320)
    s72605.place(x=10,y=355)
    s72604.place(x=10,y=390)
    s72486.place(x=10,y=425)
    s72484.place(x=10,y=460)
    s72364.place(x=10,y=495)
    # === Amount ===
    total_label = customtkinter.CTkLabel(stk,text="00",text_color='white',fg_color='red',corner_radius=7,width=78,height=78,font=customtkinter.CTkFont("Book Antiqua",30,'bold'))
    total_label.place(x=850,y=10)
    # === Galaxy ===
    a1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    a1.place(x=160,y=5)
    a2.place(x=160,y=40)
    a3.place(x=160,y=75)
    a4.place(x=160,y=110)
    a5.place(x=160,y=145)
    a6.place(x=160,y=180)
    a7.place(x=160,y=215)
    a8.place(x=160,y=250)
    a9.place(x=160,y=285)
    a10.place(x=160,y=320)
    a11.place(x=160,y=355)
    a15.place(x=160,y=495)
    a12.place(x=160,y=390)
    a13.place(x=160,y=425)
    a14.place(x=160,y=460)
    # === Health Care ===
    b1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    b1.place(x=260,y=5)
    b2.place(x=260,y=40)
    b3.place(x=260,y=75)
    b4.place(x=260,y=110)
    b5.place(x=260,y=145)
    b6.place(x=260,y=180)
    b7.place(x=260,y=215)
    b8.place(x=260,y=250)
    b9.place(x=260,y=285)
    b10.place(x=260,y=320)
    b11.place(x=260,y=355)
    b12.place(x=260,y=390)
    b13.place(x=260,y=425)
    b14.place(x=260,y=460)
    b15.place(x=260,y=495)
    # === Spine Care ===
    c1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    c1.place(x=365,y=5)
    c2.place(x=365,y=40)
    c3.place(x=365,y=75)
    c4.place(x=365,y=110)
    c5.place(x=365,y=145)
    c6.place(x=365,y=180)
    c7.place(x=365,y=215)
    c8.place(x=365,y=250)
    c9.place(x=365,y=285)
    c10.place(x=365,y=320)
    c11.place(x=365,y=355)
    c12.place(x=365,y=390)
    c13.place(x=365,y=425)
    c14.place(x=365,y=460)
    c15.place(x=365,y=495)
    # === Choice ===
    d1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    d1.place(x=455,y=5)
    d2.place(x=455,y=40)
    d3.place(x=455,y=75)
    d4.place(x=455,y=110)
    d5.place(x=455,y=145)
    d6.place(x=455,y=180)
    d7.place(x=455,y=215)
    d8.place(x=455,y=250)
    d9.place(x=455,y=285)
    d10.place(x=455,y=320)
    d11.place(x=455,y=355)
    d12.place(x=455,y=390)
    d13.place(x=455,y=425)
    d14.place(x=455,y=460)
    d15.place(x=455,y=495)
    # === Lagoon ===
    e1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    e1.place(x=535,y=5)
    e2.place(x=535,y=40)
    e3.place(x=535,y=75)
    e4.place(x=535,y=110)
    e5.place(x=535,y=145)
    e6.place(x=535,y=180)
    e7.place(x=535,y=215)
    e8.place(x=535,y=250)
    e9.place(x=535,y=285)
    e10.place(x=535,y=320)
    e11.place(x=535,y=355)
    e12.place(x=535,y=390)
    e13.place(x=535,y=425)
    e14.place(x=535,y=460)
    e15.place(x=535,y=495)
    # === Superb ===
    f1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    f1.place(x=615,y=5)
    f2.place(x=615,y=40)
    f3.place(x=615,y=75)
    f4.place(x=615,y=110)
    f5.place(x=615,y=145)
    f6.place(x=615,y=180)
    f7.place(x=615,y=215)
    f8.place(x=615,y=250)
    f9.place(x=615,y=285)
    f10.place(x=615,y=320)
    f11.place(x=615,y=355)
    f12.place(x=615,y=390)
    f13.place(x=615,y=425)
    f14.place(x=615,y=460)
    f15.place(x=615,y=495)
    # === Diamond ===
    g1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    g1.place(x=695,y=5)
    g2.place(x=695,y=40)
    g3.place(x=695,y=75)
    g4.place(x=695,y=110)
    g5.place(x=695,y=145)
    g6.place(x=695,y=180)
    g7.place(x=695,y=215)
    g8.place(x=695,y=250)
    g9.place(x=695,y=285)
    g10.place(x=695,y=320)
    g11.place(x=695,y=355)
    g12.place(x=695,y=390)
    g13.place(x=695,y=425)
    g14.place(x=695,y=460)
    g15.place(x=695,y=495)
    # === A-One ===
    h1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    h1.place(x=775,y=5)
    h2.place(x=775,y=40)
    h3.place(x=775,y=75)
    h4.place(x=775,y=110)
    h5.place(x=775,y=145)
    h6.place(x=775,y=180)
    h7.place(x=775,y=215)
    h8.place(x=775,y=250)
    h9.place(x=775,y=285)
    h10.place(x=775,y=320)
    h11.place(x=775,y=355)
    h12.place(x=775,y=390)
    h13.place(x=775,y=425)
    h14.place(x=775,y=460)
    h15.place(x=775,y=495)
    # === Sleep Ease ===
    i1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    i1.place(x=855,y=5)
    i2.place(x=855,y=40)
    i3.place(x=855,y=75)
    i4.place(x=855,y=110)
    i5.place(x=855,y=145)
    i6.place(x=855,y=180)
    i7.place(x=855,y=215)
    i8.place(x=855,y=250)
    i9.place(x=855,y=285)
    i10.place(x=855,y=320)
    i11.place(x=855,y=355)
    i12.place(x=855,y=390)
    i13.place(x=855,y=425)
    i14.place(x=855,y=460)
    i15.place(x=855,y=495)
    # === Relax ===
    j1 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j2 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j3 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j4 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j5 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j6 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j7 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j8 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j9 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j10 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j11 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j12 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='grey',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j13 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j14 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='white',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j15 = customtkinter.CTkLabel(body,text="00",width=65,height=30,fg_color='yellow',text_color='black',corner_radius=7,font=customtkinter.CTkFont("Book Antiqua",20,"bold"))
    j1.place(x=940,y=5)
    j2.place(x=940,y=40)
    j3.place(x=940,y=75)
    j4.place(x=940,y=110)
    j5.place(x=940,y=145)
    j6.place(x=940,y=180)
    j7.place(x=940,y=215)
    j8.place(x=940,y=250)
    j9.place(x=940,y=285)
    j10.place(x=940,y=320)
    j11.place(x=940,y=355)
    j12.place(x=940,y=390)
    j13.place(x=940,y=425)
    j14.place(x=940,y=460)
    j15.place(x=940,y=495) 
moiz.mainloop()